return PlaceObj('ModDef', {
	'title', "Balanced Terraforming",
	'description', "This mod rebalances terraforming technologies, buildings, expeditions and crops, and makes terraforming paramaters interdependent. A denser atmosphere traps more heat; higher temperatures cause devolatilisation from the Martian regolith; plant growth depends on atmosphere, temperature and water; and vegetation contributes to atmospheric terraforming by converting CO2 into breathable oxygen. Terraforming elements have been rebalanced around these interdependencies",
	'image', "Mars_terraforming-NASA.png",
	'id', "ubJabHW",
	'pops_desktop_uuid', "c17d64ec-7c7a-42a2-a8b0-16933f1b845c",
	'pops_any_uuid', "da3503ba-4221-41a1-b7ca-de2e740d4f59",
	'author', "Lithovore",
	'version', 10,
	'lua_revision', 233360,
	'saved_with_revision', 249143,
	'code', {
		"Code/ScriptBuildings.lua",
		"Code/ScriptInfopanel.lua",
		"Code/ScriptMissions.lua",
		"Code/ScriptParameters.lua",
		"Code/ScriptTechs.lua",
		"Code/ScriptVegetation.lua",
		"Code/Class_RDM_GeoPowerPlant.lua",
		"Code/Class_sBuilding_GeoPowerPlant.lua",
		"Code/Init.lua",
		"Code/SavegameFix.lua",
	},
	'saved', 1579318742,
	'screenshot1', "Mars_terraforming-NASA.png",
	'TagGameplay', true,
})